### ISSUE TITLE
RTD builds are failing

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.i18n#26]
See http://readthedocs.org/projects/zopei18n/builds/

And the hook doesn't seem to be active.

@tseaver could you please take a look? Or you could add me as a maintainer if you'd like.

**Comment by tseaver** [comment]
> See http://readthedocs.org/projects/zopei18n/builds/

I checked the "build in a virtualenv" box and re-triggered the builds:  both succeeded.

> And the hook doesn't seem to be active.

AFAICT the Github integration for RTD is [active](https://github.com/zopefoundation/zope.i18n/settings/installations).

> Or you could add me as a maintainer if you'd like.

@jamadden What is your RTD profile id?

**Comment by jamadden** [comment]
> I checked the "build in a virtualenv" box and re-triggered the builds:  both succeeded.

Thanks!

> AFAICT the Github integration for RTD is active.

It was missing and I added it from the github side, but a test payload didn’t seem to do anything. I guess we’ll find out on the next master commit. 

> @jamadden What is your RTD profile

Jamadden@gmail.com I think.

**Comment by tseaver** [comment]
> >    @jamadden What is your RTD profile

>  Jamadden@gmail.com I think.

Added as a maintainer.
