### ISSUE TITLE
Regression: zope.i18n 4.3.0 breaks zope.app.testing

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.i18n#30]
Something changed in zope.i18n 4.3.0 that breaks zope.app.testing:

```
Traceback (most recent call last):
  File "/home/travis/build/mgedmin/zodbbrowser/src/zodbbrowser/ftests/test_standalone.py", line 23, in <module>
    from zope.app.testing import setup
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/zope/app/testing/setup.py", line 59, in <module>
    from zope.app.testing.placelesssetup import setUp as placelessSetUp
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/zope/app/testing/placelesssetup.py", line 32, in <module>
    ContainerPlacelessSetup):
TypeError: Error when calling the metaclass bases
    Cannot create a consistent method resolution
order (MRO) for bases PlacelessSetup, PlacelessSetup, PlacelessSetup, CleanUp
```

Downgrading zope.i18n to 4.2.0 makes the problem go away.

**Comment by mgedmin** [comment]
I think I would prefer to fix this in zope.i18n rather than in the places that call it (which are zope.app.testing and Zope 2's ZopeTestCase).  This is what zope.container does in a similar situation: 
https://github.com/zopefoundation/zope.container/blob/9ea9a2559ed118d4fc2f2ee19b381b696b436578/src/zope/container/testing.py#L55-L72

**Comment by jamadden** [comment]
Fix in #32. 

I apologise for the hassle.

**Comment by mgedmin** [comment]
Not your fault -- these PlacelessSetup classes are actually mixins, but that's not reflected in their name.

Thank you for fixing this so quickly!

Do you plan to make a 4.3.1 PyPI release now, or should I do it?

**Comment by mgedmin** [comment]
> Do you plan to make a 4.3.1 PyPI release now, or should I do it?

Oh, I see you've already made it.  Thanks!
