### ISSUE TITLE
Tests are broken on master because of zope.i18nmessageid >= 7.0

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.i18n#62]
Traceback:

```python
Error in test testMessageIDRecursiveTranslate (zope.i18n.tests.test_translationdomain.TestGlobalTranslationDomain.testMessageIDRecursiveTranslate)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
  File "/home/runner/work/zope.i18n/zope.i18n/src/zope/i18n/tests/test_translationdomain.py", line 116, in testMessageIDRecursiveTranslate
    msgid1.mapping['msg2'] = msgid2
TypeError: 'mappingproxy' object does not support item assignment
```

See https://github.com/zopefoundation/zope.i18n/actions/runs/10980960593/job/30487405136

There were several packages updated but I bisected it to the update of `zope.i18nmessageid`, requiring a version `< 7` makes the tests pass.

**Comment by d-maurer** [comment]
I think the test is wrong: message ids should be hashable with a persistent hash. In general, this implies that they cannot be changed after creation. The test modifies the `mapping` attribute of the message id likely violating the persistent hash condition.

I will try to verify my thought.

**Comment by d-maurer** [comment]
https://github.com/zopefoundation/zope.i18nmessageid/blob/2fea1d9944d7eb10f8b9c97e3853cd517f5c43a9/docs/narr.rst?plain=1#L94
clearly tells that message ids are designed to be immutable; i.e. its attributes must not be changed after creation.

Apparently, previous (< 7) versions of `zope.i18nmessageid` have not enforced this fully.

**Comment by icemac** [comment]
Okay, this means: Let's fix the test.
Let me give it a try.
